name: quicklibs
description: some useful utils for Dart that include of iterator and time
version: 1.0.9
homepage: https://github.com/CimZzz/quicklibs
author: wangyanxiong <a1950207@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'
