name: quicklibs
description: Useful toolkits collection for Dart. Include of `Time`、`Iterator` and `Scope`, that very convenient to use. Be happy~ :)
version: 1.1.4
homepage: https://github.com/CimZzz/quicklibs
author: wangyanxiong <a1950207@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'
